<a href="https://colab.research.google.com/github/Santhosh-1801/DL/blob/main/TensorInputPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import tensorflow as tf

In [71]:
daily_sales_number=[21,22,-108,31,-1,32,34,31]

In [72]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)

In [73]:
for sales in tf_dataset:
  print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [74]:
tf_dataset=tf_dataset.filter(lambda x:x>0)

In [75]:
tf_dataset
for sales in tf_dataset.as_numpy_iterator():
  print(sales)


21
22
31
32
34
31


In [76]:
tf_dataset=tf_dataset.map(lambda x:x*72)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1512
1584
2232
2304
2448
2232


In [77]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda x:x*72).shuffle(2).batch(2)


Cause: could not parse the source code of <function <lambda> at 0x7fd71573f400>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: x * 72

Match 1:
lambda x: x > 0

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7fd71573f400>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: x * 72

Match 1:
lambda x: x > 0

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7fd71573eb00>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: x * 72

Match 1:
lambda x: x > 0

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7fd71573eb00>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: x * 72

Match 1:
lambda x: x > 0

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [78]:
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

[1584 2232]
[2304 2448]
[2232 1512]


In [79]:
images_ds=tf.data.Dataset.list_files('/content/sample_data/images/*/*',shuffle=False)

In [80]:
for file in images_ds.take(3):
  print(file.numpy())

b'/content/sample_data/images/cat/20 Reasons Why Cats Make the Best Pets....jpg'
b'/content/sample_data/images/cat/7 Foods Your Cat Can_t Eat.jpg'
b'/content/sample_data/images/cat/A cat appears to have caught the....jpg'


In [81]:
images_ds=images_ds.shuffle(200)


In [82]:
class_names=['cat','dog']

In [83]:
image_count=len(images_ds)

In [84]:
image_count

130

In [85]:
train_size=int(image_count*0.8)

In [86]:
train_size

104

In [87]:
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [88]:
len(test_ds)

26

In [89]:
def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[-2]


In [90]:
def process_image(file_path):
  label=get_label(file_path)
  img=tf.io.read_file(file_path)
  img=tf.image.decode_jpeg(img)
  img=tf.image.resize(img,[128,128])
  return img,label

In [91]:
train_ds=train_ds.map(process_image)


In [94]:
for image,label in train_ds.take(3):
  print("Image is ",image)
  print("Label is",label)



Image is  tf.Tensor(
[[[150.1206   169.1206   105.120605]
  [150.       169.       105.      ]
  [151.       172.       107.      ]
  ...
  [166.       176.       107.      ]
  [167.29688  175.85156  111.      ]
  [166.45654  175.01123  110.15967 ]]

 [[149.       168.       104.      ]
  [150.       169.       105.      ]
  [151.       172.       107.      ]
  ...
  [167.       178.       110.      ]
  [168.       177.       114.      ]
  [168.       177.       114.      ]]

 [[149.       168.       104.      ]
  [149.5625   168.5625   104.5625  ]
  [151.       172.       107.      ]
  ...
  [165.48438  178.25781  112.      ]
  [167.74219  178.25781  115.515625]
  [167.13916  177.65479  114.9126  ]]

 ...

 [[116.34717  140.78125   70.36572 ]
  [115.70752  134.0581    78.94531 ]
  [108.99219  128.50781   72.50781 ]
  ...
  [129.61035  137.88428   79.305176]
  [143.81152  147.69775  102.06152 ]
  [116.27197  131.99707   73.67822 ]]

 [[120.677246 139.57324   75.05762 ]
  [111.       12

In [95]:
def scale(image,label):
  return image/255,label

In [96]:
image,label=scale(image,label)

In [97]:
train_ds=train_ds.map(scale)
for image,label in train_ds.take(5):
  print("***Image is ",image.numpy()[0][0])
  print("***Label is ",label.numpy())

***Image is  [0.9059021  0.9137452  0.85884327]
***Label is  b'dog'
***Image is  [0.49607843 0.4254902  0.38627452]
***Label is  b'cat'
***Image is  [0.31072304 0.31072304 0.31072304]
***Label is  b'dog'
***Image is  [0.01691177 0.0247549  0.01409314]
***Label is  b'cat'
***Image is  [0.8365982 0.7634508 0.52577  ]
***Label is  b'dog'
