<a href="https://colab.research.google.com/github/Santhosh-1801/DL/blob/main/WordEmbeddingusingKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews=[
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it',
    'will go again',
    'horrible again',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

In [ ]:
sentiments=np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
sentiments


array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [ ]:
one_hot('amazing restaurant',50)

[11, 15]

In [ ]:
vocab_size=30
encoded_reviews=[one_hot(review,vocab_size) for review in reviews]

In [ ]:
encoded_reviews

[[26, 24],
 [9, 21],
 [15, 26],
 [9, 16, 22],
 [14, 10, 8],
 [14, 8],
 [17, 10, 17],
 [2, 12],
 [2, 9],
 [11, 9]]

In [ ]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[26 24  0  0]
 [ 9 21  0  0]
 [15 26  0  0]
 [ 9 16 22  0]
 [14 10  8  0]
 [14  8  0  0]
 [17 10 17  0]
 [ 2 12  0  0]
 [ 2  9  0  0]
 [11  9  0  0]]


In [ ]:
embedded_vector_size=4
model=Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='Embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [ ]:
X=padded_reviews
y=sentiments



In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Embedding (Embedding)       (None, 4, 4)              120       
                                                                 
 flatten_3 (Flatten)         (None, 16)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X,y,epochs=50,verbose=0)

In [ ]:
loss,accuracy=model.evaluate(X,y)

1/1 [==============================] - 0s 147ms/step - loss: 0.6439 - accuracy: 1.0000


In [ ]:
model.get_layer('Embedding').get_weights()[0]

array([[ 0.00052365,  0.03285252,  0.00156982, -0.07652572],
       [-0.00648736,  0.03688138,  0.0351712 ,  0.02043065],
       [-0.05068492, -0.09056158,  0.10159572,  0.08095158],
       [ 0.00287656, -0.04127761, -0.01162688,  0.00494038],
       [-0.04912515,  0.00117197, -0.00166229, -0.02932332],
       [-0.01709666,  0.04413667,  0.04906556, -0.01675237],
       [ 0.00273982,  0.02003506, -0.01513974, -0.01344746],
       [-0.04718331, -0.02717379,  0.04059483,  0.04178505],
       [ 0.01920743, -0.00753468,  0.08332451,  0.02899408],
       [ 0.01500047,  0.00649025, -0.03457655, -0.06851833],
       [ 0.00964435, -0.02759644, -0.06909756,  0.00042215],
       [-0.03564284, -0.04629998,  0.07643721,  0.05739219],
       [-0.00814399,  0.05579358,  0.04721105,  0.04213833],
       [ 0.0455021 ,  0.0331446 , -0.00751829, -0.02981674],
       [ 0.03868223,  0.00941543,  0.00627031, -0.03374864],
       [ 0.06849321,  0.01741912, -0.08634821, -0.0817487 ],
       [ 0.04291892, -0.